Id: EclipseFoundation.Mosquitto
Version: 1.6.9
Name: Eclipse Mosquitto
Publisher: Eclipse Foundation
Homepage: https://mosquitto.org/
License: EPL-2.0 / EDL-2.0
Description: Mosquitto MQTT broker
AppMoniker: mosquitto
Installers:
  - Arch: x64
    Url: https://mosquitto.org/files/binary/win64/mosquitto-1.6.9-install-windows-x64.exe
    InstallerType: exe
    Sha256: dcdfe445dcb35bea0d62e7f7fc0ff9946da5122e5fefca7f9e0dae179c7a6665
